GET http://localhost:5001/

###

GET http://localhost:5001/api/movies

###

GET http://localhost:5001/api/movies/384018
//http://localhost:5001/api/movies/:moviesid

###

//how to send?
//this is an example for a specific movie, how do we get all in a genre by year?
//https://api.themoviedb.org/3/movie/76341?api_key=<<api_key>>
//with a movie description, list of actors, and director?


// top-rated
// 
GET http://localhost:5001/api/movies/top_rated

###

// "genres"
GET http://localhost:5001/api/genres


###

// "poster_path", "release_date", "title", "vote_average"
GET http://localhost:5001/api/discover/2020/12/1

###

GET https://api.themoviedb.org/3/account?api_key=ad65f3f346cc7869630deac544b0f1f7

###

// "secure_base_url", "poster_sizes" - 404 error
GET http://localhost:5001/api/configuration

###

// hardcoded, not running through server
GET https://api.themoviedb.org/3/configuration?api_key=ad65f3f346cc7869630deac544b0f1f7

###

// credits - all directors, actors, and other crew
GET http://localhost:5001/api/movies/384018/credits
